# JVM para el daemon de Gradle
org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8 -XX:+UseParallelGC
# AndroidX obligatorio
android.useAndroidX=true
# Una clase R por módulo (build más rápido)
android.nonTransitiveRClass=true
# Estilo de código Kotlin
kotlin.code.style=official
# Nombres completos de tareas en el log de CI
org.gradle.console=plain
