package defpackage;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;

/* renamed from: by8  reason: default package */
/* compiled from: r8-map-id-a2600502e373284585f18be1dd969014ce4136ee711daf2a2a8e9cf573c31dbd */
public abstract class by8 {
    public static final ay8 A = a("measurement.sgtm.upload.max_queued_batches", 5000, hr2.D, false);
    public static final ay8 A0 = a("measurement.rb.attribution.notify_app_delay_millis", 3000, z53.I, false);
    public static final ay8 B = a("measurement.sgtm.upload.batches_retrieval_limit", 5, or2.A, false);
    public static final ay8 B0 = a("measurement.upload.diagnostic_upload_interval", 3600000L, s63.J, false);
    public static final ay8 C = a("measurement.sgtm.upload.min_delay_after_startup", 5000L, ts2.A, false);
    public static final ay8 C0;
    public static final ay8 D = a("measurement.sgtm.upload.min_delay_after_broadcast", 1000L, jv2.C, false);
    public static final ay8 D0;
    public static final ay8 E = a("measurement.sgtm.upload.min_delay_after_background", 600000L, tz2.B, false);
    public static final ay8 E0;
    public static final ay8 F = a("measurement.sgtm.batch.long_queuing_threshold", 14400000L, z53.B, false);
    public static final ay8 F0;
    public static final ay8 G = a("measurement.upload.backoff_period", 43200000L, s63.C, false);
    public static final ay8 G0;
    public static final ay8 H = a("measurement.upload.interval", 3600000L, or2.B, false);
    public static final ay8 H0;
    public static final ay8 I = a("measurement.upload.realtime_upload_interval", 10000L, ts2.B, false);
    public static final ay8 I0;
    public static final ay8 J = a("measurement.upload.debug_upload_interval", 1000L, jv2.D, false);
    public static final ay8 J0 = a("measurement.service.storage_consent_support_version", 203600, dx8.x, false);
    public static final ay8 K = a("measurement.upload.minimum_delay", 500L, z53.C, false);
    public static final ay8 K0;
    public static final ay8 L = a("measurement.alarm_manager.minimum_interval", 60000L, s63.D, false);
    public static final ay8 L0;
    public static final ay8 M = a("measurement.upload.stale_data_deletion_interval", 86400000L, hr2.F, false);
    public static final ay8 M0;
    public static final ay8 N = a("measurement.upload.refresh_blacklisted_config_interval", 604800000L, ts2.C, false);
    public static final ay8 N0;
    public static final ay8 O = a("measurement.upload.initial_upload_delay_time", 15000L, jv2.E, false);
    public static final ay8 O0;
    public static final ay8 P = a("measurement.upload.retry_time", 1800000L, z53.D, false);
    public static final ay8 P0;
    public static final ay8 Q = a("measurement.upload.retry_count", 6, n63.C, false);
    public static final ay8 Q0;
    public static final ay8 R = a("measurement.upload.max_queue_time", 518400000L, s63.E, false);
    public static final ay8 R0;
    public static final ay8 S = a("measurement.upload.google_signal_max_queue_time", 300000L, hr2.G, false);
    public static final ay8 S0;
    public static final ay8 T = a("measurement.lifetimevalue.max_currency_tracked", 4, or2.C, false);
    public static final ay8 T0;
    public static final ay8 U = a("measurement.audience.filter_result_max_count", 200, ts2.D, false);
    public static final ay8 U0;
    public static final ay8 V = a("measurement.upload.max_public_user_properties", 100, (fs8) null, false);
    public static final ay8 V0;
    public static final ay8 W = a("measurement.upload.max_event_name_cardinality", 2000, (fs8) null, false);
    public static final ay8 W0;
    public static final ay8 X = a("measurement.upload.max_public_event_params", 100, (fs8) null, false);
    public static final ay8 X0;
    public static final ay8 Y = a("measurement.service_client.idle_disconnect_millis", 5000L, jv2.F, false);
    public static final ay8 Y0;
    public static final ay8 Z = a("measurement.service_client.reconnect_millis", 1000L, tz2.D, false);
    public static final ay8 Z0;
    public static final List a = Collections.synchronizedList(new ArrayList());
    public static final ay8 a0;
    public static final ay8 a1;
    public static final ay8 b = a("measurement.ad_id_cache_time", 10000L, dx8.z, false);
    public static final ay8 b0 = a("measurement.test.test_string_flag", "---", n63.D, false);
    public static final ay8 b1 = a("measurement.gbraid_compaign.compaign_params_triggering_info_update", "gclid,gbraid,gad_campaignid", tz2.y, false);
    public static final ay8 c = a("measurement.app_uninstalled_additional_ad_id_cache_time", 3600000L, jv2.z, false);
    public static final ay8 c0 = a("measurement.test.test_long_flag", -1L, hr2.H, false);
    public static final ay8 c1;
    public static final ay8 d = a("measurement.monitoring.sample_period_millis", 86400000L, jv2.B, false);
    public static final ay8 d0 = a("measurement.test.test_int_flag", -2, ts2.E, false);
    public static final ay8 d1 = a("measurement.edpb.events_cached_in_no_data_mode", "_f,_v,_cmp", z53.y, false);
    public static final ay8 e = a("measurement.config.cache_time", 86400000L, n63.B, false);
    public static final ay8 e0 = a("measurement.test.test_double_flag", Double.valueOf(-3.0d), jv2.G, false);
    public static final ay8 e1;
    public static final ay8 f = a("measurement.config.url_scheme", "https", tz2.C, false);
    public static final ay8 f0 = a("measurement.upload.max_item_scoped_custom_parameters", 27, z53.F, false);
    public static final ay8 f1;
    public static final ay8 g = a("measurement.config.url_authority", "app-measurement.com", s63.F, false);
    public static final ay8 g0 = a("measurement.upload.max_event_parameter_value_length", 500, n63.E, true);
    public static final ay8 g1 = a("measurement.dsid_consent_only.app_allowlist1", "", n63.y, false);
    public static final ay8 h = a("measurement.upload.max_bundles", 100, ts2.F, false);
    public static final ay8 h0 = a("measurement.max_bundles_per_iteration", 100, s63.G, false);
    public static final ay8 h1 = a("measurement.dsid_consent_only.app_allowlist2", "", s63.z, false);
    public static final ay8 i = a("measurement.upload.max_batch_size", 65536, z53.H, false);
    public static final ay8 i0 = a("measurement.sdk.attribution.cache.ttl", 604800000L, hr2.I, false);
    public static final ay8 i1 = a("measurement.dsid_consent_only.app_allowlist3", "", hr2.B, false);
    public static final ay8 j = a("measurement.upload.max_bundle_size", 65536, hr2.L, false);
    public static final ay8 j0 = a("measurement.redaction.app_instance_id.ttl", 7200000L, or2.E, false);
    public static final ay8 j1;
    public static final ay8 k = a("measurement.upload.max_events_per_bundle", 1000, lx8.x, false);
    public static final ay8 k0 = a("measurement.rb.attribution.client.min_ad_services_version", 7, jv2.H, false);
    public static final ay8 l = a("measurement.upload.max_events_per_day", 100000, rx8.y, false);
    public static final ay8 l0 = a("measurement.dma_consent.max_daily_dcu_realtime_events", 1, tz2.F, false);
    public static final ay8 m = a("measurement.upload.max_error_events_per_day", 1000, or2.y, false);
    public static final ay8 m0 = a("measurement.rb.attribution.uri_scheme", "https", z53.G, false);
    public static final ay8 n = a("measurement.upload.max_public_events_per_day", 50000, ts2.y, false);
    public static final ay8 n0 = a("measurement.rb.attribution.uri_authority", "google-analytics.com", n63.F, false);
    public static final ay8 o = a("measurement.upload.max_conversions_per_day", 10000, jv2.A, false);
    public static final ay8 o0 = a("measurement.rb.attribution.uri_path", "privacy-sandbox/register-app-conversion", s63.H, false);
    public static final ay8 p = a("measurement.upload.max_realtime_events_per_day", 10, tz2.z, false);
    public static final ay8 p0 = a("measurement.session.engagement_interval", 3600000L, hr2.J, false);
    public static final ay8 q = a("measurement.store.max_stored_events_per_app", 100000, z53.z, false);
    public static final ay8 q0 = a("measurement.rb.attribution.app_allowlist", "", or2.F, false);
    public static final ay8 r = a("measurement.upload.url", "https://app-measurement.com/a", n63.z, false);
    public static final ay8 r0 = a("measurement.rb.attribution.user_properties", "_npa,npa|_fot,fot", ts2.G, false);
    public static final ay8 s = a("measurement.sgtm.google_signal.url", "https://app-measurement.com/s/d", s63.A, false);
    public static final ay8 s0 = a("measurement.rb.attribution.event_params", "value|currency", jv2.I, false);
    public static final ay8 t = a("measurement.sgtm.service_upload_apps_list", "", hr2.C, false);
    public static final ay8 t0 = a("measurement.rb.attribution.query_parameters_to_remove", "", tz2.G, false);
    public static final ay8 u = a("measurement.sgtm.upload.backoff_http_codes", "404,429,503,504", or2.z, false);
    public static final ay8 u0 = a("measurement.rb.attribution.max_queue_time", 864000000L, n63.G, false);
    public static final ay8 v = a("measurement.sgtm.upload.retry_interval", 600000L, ts2.z, false);
    public static final ay8 v0 = a("measurement.rb.attribution.max_retry_delay_seconds", 16, s63.I, false);
    public static final ay8 w = a("measurement.sgtm.upload.retry_max_wait", 21600000L, tz2.A, false);
    public static final ay8 w0 = a("measurement.rb.attribution.client.min_time_after_boot_seconds", 90, hr2.K, false);
    public static final ay8 x = a("measurement.sgtm.batch.retry_interval", 1800000L, z53.A, false);
    public static final ay8 x0 = a("measurement.rb.max_trigger_registrations_per_day", 1000, ts2.H, false);
    public static final ay8 y = a("measurement.sgtm.batch.retry_max_wait", 21600000L, n63.A, false);
    public static final ay8 y0;
    public static final ay8 z = a("measurement.sgtm.batch.retry_max_count", 10, s63.B, false);
    public static final ay8 z0;

    static {
        Collections.synchronizedSet(new HashSet());
        a("measurement.upload.window_interval", 3600000L, hr2.E, false);
        Boolean bool = Boolean.FALSE;
        a0 = a("measurement.test.test_boolean_flag", bool, z53.E, false);
        a("measurement.test.test_cached_long_flag", -1L, or2.D, true);
        a("measurement.experiment.max_ids", 50, tz2.E, false);
        a("measurement.rb.attribution.max_trigger_uris_queried_at_once", 0, or2.G, false);
        Boolean bool2 = Boolean.TRUE;
        y0 = a("measurement.config.bundle_for_all_apps_on_backgrounded", bool2, jv2.J, false);
        z0 = a("measurement.config.notify_trigger_uris_on_backgrounded", bool2, tz2.H, false);
        a("measurement.config.default_flag_values", bool2, n63.H, false);
        C0 = a("measurement.quality.checksum", bool, (fs8) null, false);
        D0 = a("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", bool, or2.H, false);
        E0 = a("measurement.audience.refresh_event_count_filters_timestamp", bool, ts2.I, false);
        F0 = a("measurement.audience.use_bundle_timestamp_for_event_count_filters", bool, jv2.K, true);
        G0 = a("measurement.sdk.collection.last_deep_link_referrer_campaign2", bool, tz2.I, false);
        H0 = a("measurement.integration.disable_firebase_instance_id", bool, z53.J, false);
        I0 = a("measurement.collection.service.update_with_analytics_fix", bool, n63.I, false);
        K0 = a("measurement.service.store_null_safelist", bool2, fx8.x, false);
        L0 = a("measurement.service.store_safelist", bool2, hx8.x, false);
        M0 = a("measurement.session_stitching_token_enabled", bool, jx8.x, false);
        N0 = a("measurement.sgtm.client.upload_on_backgrounded.dev", bool, nx8.x, true);
        O0 = a("measurement.rb.attribution.service", bool2, px8.x, true);
        P0 = a("measurement.rb.attribution.client2", bool2, rx8.x, true);
        Q0 = a("measurement.rb.attribution.uuid_generation", bool2, dx8.y, false);
        R0 = a("measurement.rb.attribution.enable_trigger_redaction", bool2, fx8.y, false);
        S0 = a("measurement.client.sessions.enable_fix_background_engagement", bool2, nx8.z, false);
        a("measurement.rb.attribution.service.enable_max_trigger_uris_queried_at_once", bool2, hx8.y, false);
        a("measurement.remove_conflicting_first_party_apis.dev", bool, jx8.y, false);
        T0 = a("measurement.rb.attribution.service.trigger_uris_high_priority", bool2, lx8.y, false);
        U0 = a("measurement.experiment.enable_phenotype_experiment_reporting", bool2, nx8.y, false);
        V0 = a("measurement.experiment.enable_passthrough_experiment_reporting", bool2, px8.y, false);
        W0 = a("measurement.set_default_event_parameters.fix_service_request_ordering", bool, s63.y, false);
        X0 = a("measurement.set_default_event_parameters.fix_app_update_logging", bool2, n63.x, false);
        Y0 = a("measurement.service.fix_stop_bundling_bug", bool2, ts2.x, false);
        Z0 = a("measurement.gbraid_campaign.stop_lgclid", bool, hx8.z, false);
        a1 = a("measurement.gbraid_campaign.deep_link_url", bool, fx8.z, false);
        c1 = a("measurement.edpb.service", bool, or2.x, false);
        e1 = a("measurement.robust_time_source_2", bool, lx8.z, false);
        f1 = a("measurement.manual_iap_logging.client_service", bool, jx8.z, false);
        j1 = a("measurement.diagnostics.enabled", bool, hr2.A, false);
    }

    public static ay8 a(String str, Object obj, fs8 fs8, boolean z2) {
        ay8 ay8 = new ay8(str, obj, fs8);
        if (z2) {
            a.add(ay8);
        }
        return ay8;
    }
}
