package defpackage;

/* renamed from: kt0  reason: default package */
/* compiled from: r8-map-id-a2600502e373284585f18be1dd969014ce4136ee711daf2a2a8e9cf573c31dbd */
public abstract class kt0 {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D = ac5.h;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long J = ac5.o;
    public static final long K = ac5.k;
    public static final long L = ac5.l;
    public static final long M = ac5.n;
    public static final long N = ac5.i;
    public static final long O = ac5.p;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final long S;
    public static final long T;
    public static final long U;
    public static final long a;
    public static final long b = ac5.f;
    public static final long c = ac5.d;
    public static final long d = ac5.m;
    public static final long e = ac5.H;
    public static final long f;
    public static final long g;
    public static final long h = ac5.c;
    public static final long i = ac5.g;
    public static final long j = ac5.F;
    public static final long k;
    public static final long l = ac5.D;
    public static final long m;
    public static final long n = ac5.M;
    public static final long o;
    public static final long p = ac5.K;
    public static final long q;
    public static final long r;
    public static final long s = ac5.B;
    public static final long t = ac5.T;
    public static final long u;
    public static final long v = ac5.R;
    public static final long w;
    public static final long x = ac5.A;
    public static final long y;
    public static final long z;

    static {
        long j2 = ac5.q;
        a = j2;
        long j3 = ac5.s;
        f = j3;
        g = j3;
        long j4 = ac5.J;
        k = j4;
        long j5 = ac5.G;
        m = j5;
        long j6 = ac5.Q;
        o = j6;
        long j7 = ac5.N;
        q = j7;
        r = j3;
        long j8 = ac5.X;
        u = j8;
        long j9 = ac5.U;
        w = j9;
        long j10 = ac5.y;
        y = j10;
        long j11 = ac5.I;
        z = j11;
        A = j5;
        B = j4;
        C = j11;
        long j12 = ac5.P;
        E = j12;
        F = j7;
        G = j6;
        H = j12;
        I = j2;
        P = j2;
        Q = j10;
        long j13 = ac5.W;
        R = j13;
        S = j9;
        T = j8;
        U = j13;
    }
}
