package defpackage;

/* renamed from: zp7  reason: default package */
/* compiled from: r8-map-id-a2600502e373284585f18be1dd969014ce4136ee711daf2a2a8e9cf573c31dbd */
public abstract class zp7 {
    public static final long A = ya5.j(44.0d);
    public static final long B = ya5.k(36);
    public static final long C = ya5.j(0.0d);
    public static final am2 D;
    public static final fv2 E;
    public static final long F = ya5.j(40.0d);
    public static final long G = ya5.k(32);
    public static final long H = ya5.j(0.0d);
    public static final am2 I;
    public static final fv2 J;
    public static final long K = ya5.j(36.0d);
    public static final long L = ya5.k(28);
    public static final long M = ya5.j(0.0d);
    public static final am2 N;
    public static final fv2 O;
    public static final long P = ya5.j(32.0d);
    public static final long Q = ya5.k(24);
    public static final long R = ya5.j(0.0d);
    public static final am2 S;
    public static final fv2 T;
    public static final long U = ya5.j(20.0d);
    public static final long V = ya5.k(14);
    public static final long W = ya5.j(0.1d);
    public static final am2 X;
    public static final fv2 Y;
    public static final long Z = ya5.j(16.0d);
    public static final fv2 a;
    public static final long a0 = ya5.k(12);
    public static final long b = ya5.j(24.0d);
    public static final long b0 = ya5.j(0.5d);
    public static final long c = ya5.k(16);
    public static final am2 c0;
    public static final long d = ya5.j(0.5d);
    public static final fv2 d0;
    public static final am2 e;
    public static final long e0 = ya5.j(16.0d);
    public static final fv2 f;
    public static final long f0 = ya5.k(11);
    public static final long g = ya5.j(20.0d);
    public static final long g0 = ya5.j(0.5d);
    public static final long h = ya5.k(14);
    public static final am2 h0;
    public static final long i = ya5.j(0.2d);
    public static final fv2 i0;
    public static final am2 j;
    public static final long j0 = ya5.j(28.0d);
    public static final fv2 k;
    public static final long k0 = ya5.k(22);
    public static final long l = ya5.j(16.0d);
    public static final long l0 = ya5.j(0.0d);
    public static final long m = ya5.k(12);
    public static final am2 m0;
    public static final long n = ya5.j(0.4d);
    public static final fv2 n0;
    public static final am2 o;
    public static final long o0 = ya5.j(24.0d);
    public static final fv2 p;
    public static final long p0 = ya5.k(16);
    public static final long q = ya5.j(64.0d);
    public static final long q0 = ya5.j(0.2d);
    public static final long r = ya5.k(57);
    public static final am2 r0;
    public static final long s;
    public static final fv2 s0;
    public static final am2 t;
    public static final long t0 = ya5.j(20.0d);
    public static final fv2 u;
    public static final long u0 = ya5.k(14);
    public static final long v = ya5.j(52.0d);
    public static final long v0 = ya5.j(0.1d);
    public static final long w = ya5.k(45);
    public static final am2 w0;
    public static final long x = ya5.j(0.0d);
    public static final am2 y;
    public static final fv2 z;

    static {
        am2 am2 = xq7.a;
        fv2 fv2 = ea7.b;
        a = fv2;
        am2 am22 = xq7.b;
        e = am22;
        f = fv2;
        j = am22;
        k = fv2;
        o = am22;
        p = fv2;
        long j2 = ya5.j(0.2d);
        xg7[] xg7Arr = wg7.b;
        long j3 = j2 & 1095216660480L;
        if (j3 == 0) {
            ac3.a("Cannot perform operation for Unspecified type.");
        }
        s = ya5.m(-wg7.c(j2), j3);
        t = am22;
        u = fv2;
        y = am22;
        z = fv2;
        D = am22;
        E = fv2;
        I = am22;
        J = fv2;
        N = am22;
        O = fv2;
        S = am22;
        T = fv2;
        am2 am23 = xq7.a;
        X = am23;
        Y = fv2;
        c0 = am23;
        d0 = fv2;
        h0 = am23;
        i0 = fv2;
        m0 = am22;
        n0 = fv2;
        r0 = am23;
        s0 = fv2;
        w0 = am23;
        ya5.j(24.0d);
        ya5.k(16);
        ya5.j(0.15d);
        ya5.j(20.0d);
        ya5.k(14);
        ya5.j(0.25d);
        ya5.j(16.0d);
        ya5.k(12);
        ya5.j(0.4d);
        ya5.j(64.0d);
        ya5.k(57);
        ya5.k(0);
        ya5.j(52.0d);
        ya5.k(45);
        ya5.k(0);
        ya5.j(44.0d);
        ya5.k(36);
        ya5.k(0);
        ya5.j(40.0d);
        ya5.k(32);
        ya5.k(0);
        ya5.j(36.0d);
        ya5.k(28);
        ya5.k(0);
        ya5.j(32.0d);
        ya5.k(24);
        ya5.k(0);
        ya5.j(20.0d);
        ya5.k(14);
        ya5.j(0.1d);
        ya5.j(16.0d);
        ya5.k(12);
        ya5.j(0.5d);
        ya5.j(16.0d);
        ya5.k(11);
        ya5.j(0.5d);
        ya5.j(28.0d);
        ya5.k(22);
        ya5.k(0);
        ya5.j(24.0d);
        ya5.k(16);
        ya5.j(0.15d);
        ya5.j(20.0d);
        ya5.k(14);
        ya5.j(0.1d);
    }
}
